name: Проверка лейблов fixup и autosquah
on:
  pull_request:

jobs:
  message-check:
    name: Блокирование мерджа, если есть лейблы fixup или squash

    runs-on: ubuntu-latest

    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
